#
# Podfile
# Bundles
#

# http://blog.cocoapods.org/CocoaPods-1.7.0-beta/#multiple-xcodeproj-generation
install! 'cocoapods',
  generate_multiple_pod_projects: true,
  incremental_installation: true

use_frameworks!
platform :ios, '13.0'

target 'Bundles_Example' do
  supports_swift_versions '>= 5.0'

  pod 'Bundles', path: '../'

  target 'Bundles_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.5'
  end
end
