#
# Podfile
# Bundles
#

use_frameworks!

target 'Bundles_Example' do
  pod 'Bundles', :path => '../'

  target 'Bundles_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
